spring.datasource.url: jdbc:postgresql://localhost:5432/blog_engine
spring.datasource.username: natalia
spring.datasource.password: test123
spring.liquibase.change-log: classpath:/db/changelog/changelog-master.xml

spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update

init.title: DevPub
init.subtitle: Developer stories
init.phone: +7 903 666-44-55
init.email: mail@mail.ru
init.copyright: Dmitry Sergeev
init.copyrightFrom: 2005

jwt.token.secret: jwtappdemo
jwt.token.expired: 54000000

captcha.token.live: 3600000

cron.expression.captcha.del: "0 */10 * * * *"
cron.expression.code.del: "0 0 */1 * * *"

hibernate.search.default.directory_provider: filesystem
hibernate.search.default.indexBase: /data/index/default

spring.email.host: smtp.yandex.ua
spring.email.username: devpub@sendel.ru
spring.email.password: s&vnEN}>8rUz\9yM
spring.email.port: 465
spring.email.protocol: smtps
mail.debug: true
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtps.starttls.enable: true

host: http://localhost:8080